=== sayonatinnofied/Documents/TIBCO_TUTORIAL/TibcoPractice/File/Shared Variables/Schemas/BW_shipping_costs.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--Generated by XML Authority. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema">
	<xsd:element name = "shipping_costs">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "destination" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "destination">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "region"/>
				<xsd:element ref = "costs" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "region" type = "xsd:string"/>
	<xsd:element name = "costs">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "max_purchase_price"/>
				<xsd:element ref = "shipping_total"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "max_purchase_price" type = "xsd:integer"/>
	<xsd:element name = "shipping_total" type = "xsd:integer"/>
</xsd:schema>

=== sayonatinnofied/Documents/TIBCO_TUTORIAL/TibcoPractice/File/Shared Variables/Schemas/BW_shipping_costs.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<shipping_costs xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "BW_shipping_costs.xsd">  
	<destination>
		<region>USA</region>
		<costs>  
			<max_purchase_price>50</max_purchase_price>  
			<shipping_total>20</shipping_total>
		</costs>
		<costs>  
			<max_purchase_price>250</max_purchase_price>  
			<shipping_total>40</shipping_total>
		</costs>
		<costs>  
			<max_purchase_price>500</max_purchase_price>  
			<shipping_total>60</shipping_total>
		</costs>  
	</destination>  
	<destination>
		<region>EMEA</region>
		<costs>  
			<max_purchase_price>50</max_purchase_price>  
			<shipping_total>60</shipping_total>
		</costs>
		<costs>  
			<max_purchase_price>250</max_purchase_price>  
			<shipping_total>80</shipping_total>
		</costs>
		<costs>  
			<max_purchase_price>500</max_purchase_price>  
			<shipping_total>100</shipping_total>
		</costs>  
	</destination>  
	<destination>
		<region>Australasia</region>
		<costs>  
			<max_purchase_price>50</max_purchase_price>  
			<shipping_total>60</shipping_total>
		</costs>
		<costs>  
			<max_purchase_price>250</max_purchase_price>  
			<shipping_total>80</shipping_total>
		</costs>
		<costs>  
			<max_purchase_price>500</max_purchase_price>  
			<shipping_total>100</shipping_total>
		</costs>  
	</destination>  
	<destination>
		<region>Americas</region>
		<costs>  
			<max_purchase_price>50</max_purchase_price>  
			<shipping_total>60</shipping_total>
		</costs>
		<costs>  
			<max_purchase_price>250</max_purchase_price>  
			<shipping_total>80</shipping_total>
		</costs>
		<costs>  
			<max_purchase_price>500</max_purchase_price>  
			<shipping_total>100</shipping_total>
		</costs>  
	</destination>
</shipping_costs>
